#!/bin/bash

repo_path=$PWD

export PATH="$repo_path/trunk/SCRIPTS:$PATH"
module load cray-netcdf/4.4.1.1 
palm_simple_build -b ifort.titan -w "/lustre/atlas1/cli127/proj-shared/vanroek/palm/jobs/smallLES/"
