#!/bin/bash

use_hdf5="True"
repo_path=$PWD
build_path="/lustre/scratch3/turquoise/lvanroekel/palm/jobs/diurnal/"

export PATH="$repo_path/trunk/SCRIPTS:$PATH"
module purge
module use -a /usr/projects/climate/SHARED_CLIMATE/modulefiles/all
if [[ $use_hdf5 == "True" ]]; then
    module load intel/18.0.2
    module load openmpi/2.1.2
    module load hdf5/1.10.2
    module load netcdf/4.6.1_hdf5
    palm_simple_build -b ifort.grizzly_hdf5 -w $build_path
else
    module load intel/17.0.1
    module load openmpi/1.10.5
    module use -a /usr/projects/climate/SHARED_CLIMATE/modulefiles/all
    module load netcdf/4.4.1
    palm_simple_build -b ifort.grizzly -w $build_path
fi
