#!/bin/bash

do_coupled="False"
do_restart="False"
# number of cores for atmosphere and ocean, respectively, only used when do_coupled = True
# atm_cores + ocn_cores should be equal to $SLURM_NTASKS
atm_cores=32
ocn_cores=32
test_case="test_oceanml"
run_config="mpirun"
openmp_threads=1
repo_path=$PWD
exec_path="/home/qingli/work/palm/run/"

repo_path=$PWD
cd $SLURM_SUBMIT_DIR
export PATH="$repo_path/trunk/SCRIPTS:${PATH}"
module purge
module load pgi/18.7
module load openmpi/3.1.2-pgi_18.7
module load netcdf/4.6.1-pgi_18.7

#get ntasks and nprocs from SLURM variables
NTASKS=4
nnodes=1
NN=$((NTASKS/nnodes))

echo "PROCS = $NN"

# set options for palm_simple_run
palm_options="-w $exec_path -c $run_config -s $test_case -n $NN -p $NTASKS -t $openmp_threads"

palm_options="$palm_options -b pgi.darwin"

if [[ $do_restart == "True" ]]; then
    palm_options="$palm_options -r"
fi

if [[ $do_coupled == "True" ]]; then
    palm_simple_run $palm_options -Y "$atm_cores $ocn_cores"
else
    palm_simple_run $palm_options
fi
