#!/bin/bash

#SBATCH  --job-name=PALM_TEST
#SBATCH  --nodes=2
#SBATCH  --ntasks-per-node=32
#SBATCH  --output=PALM_TEST.%j
#SBATCH  --exclusive
#SBATCH --qos=interactive
#SBATCH --time=01:00:00
#SBATCH -A w17_mpasles

use_hdf5="True"
repo_path=$PWD
exec_path="/lustre/scratch3/turquoise/qingli/palm/jobs/diurnal"

cd $SLURM_SUBMIT_DIR
export PATH="$repo_path/trunk/SCRIPTS:${PATH}"
module use -a /usr/projects/climate/SHARED_CLIMATE/modulefiles/all
module purge

#get ntasks and nprocs from SLURM variables
NTASKS=$SLURM_NTASKS
nnodes=$SLURM_JOB_NUM_NODES
NN=$((NTASKS/nnodes))

echo "PROCS = $NP"

timestring=`squeue -h -j $SLURM_JOBID -o "%l"`
WTIME=`echo $timestring | sed -E 's/(.*):(.+):(.+)/\1*3600+\2*60+\3/;s/(.+):(.+)/\1*60+\2/' | bc`

echo "WTITME = $WTIME"

if [[ $use_hdf5 == "True" ]]; then
    module load intel/18.0.2
    module load openmpi/2.1.2
    module load hdf5/1.10.2
    module load netcdf/4.6.1_hdf5
    palm_simple_run -b ifort.grizzly_hdf5 -w $exec_path -c mpirun -s test_oceanml -n $NN -p $NTASKS -t 1 -T $WTIME
else
    module load intel/17.0.1
    module load openmpi/1.10.5
    module load netcdf/4.4.1
    palm_simple_run -b ifort.grizzly -w $exec_path -c mpirun -s test_oceanml -n $NN -p $NTASKS -t 1 -T $WTIME
fi

