#!/bin/bash

#SBATCH  --job-name=PALM_TEST
#SBATCH  --nodes=8
#SBATCH  --ntasks-per-node=32
#SBATCH  --output=PALM_TEST.%j
#SBATCH  --exclusive
#SBATCH --qos=interactive
#SBATCH --time=01:00:00
#SBATCH -A climateacme

use_hdf5="True"
repo_path=$PWD
exec_path="/lustre/scratch3/turquoise/lvanroekel/palm/jobs/diurnal" 

cd $SLURM_SUBMIT_DIR
export PATH="$repo_path/trunk/SCRIPTS:${PATH}"

if [[ $use_hdf5 == "True" ]]; then
    module load intel/18.0.2
    module load openmpi/2.1.2
    module load hdf5/1.10.2
    module load netcdf/4.6.1_hdf5
    palm_simple_run -b ifort.grizzly_hdf5 -w $exec_path -c mpirun -s test_oceanml -n 8 -p 256 -t 1
else
    module load intel/17.0.1
    module load openmpi/1.10.5
    module use -a /usr/projects/climate/SHARED_CLIMATE/modulefiles/all
    module load netcdf/4.4.1
    palm_simple_run -b ifort.grizzly -w $exec_path -c mpirun -s test_oceanml -n 8 -p 256 -t 1
fi

