#!/bin/bash

do_coupled="False"
do_restart="False"
# number of cores for atmosphere and ocean, respectively, only used when do_coupled = True
# atm_cores + ocn_cores should be equal to $SLURM_NTASKS
atm_cores=32
ocn_cores=32
test_case="test_gpu"
run_config="mpirun"
openmp_threads=1

# build_config="pgi.darwin"
build_config="pgi.darwin_mpi"

# repo_path=${PWD}
# scratch_path="/path/to/scratch/directory/"
repo_path="$HOME/models/palm_les_lanl"
scratch_path="$HOME/work/palm/run/"
script_path="$repo_path/trunk/SCRIPTS"

export PATH="$script_path:${PATH}"
module purge
module load pgi/18.7
module load openmpi/3.1.2-pgi_18.7
module load netcdf/4.6.1-pgi_18.7

#get ntasks and nprocs from SLURM variables
NTASKS=4
nnodes=1
NN=$((NTASKS/nnodes))

echo "PROCS = $NN"

# set options for palm_simple_run
palm_options="-w $scratch_path -d $script_path -c $run_config -s $test_case -n $NN -p $NTASKS -t $openmp_threads -b $build_config"

if [[ $do_restart == "True" ]]; then
    palm_options="$palm_options -r"
fi

if [[ $do_coupled == "True" ]]; then
    palm_simple_run $palm_options -Y "$atm_cores $ocn_cores"
else
    palm_simple_run $palm_options
fi
